name: Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'ci: bump version')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "ci: bump version"

      - name: Push version bump to main
        run: git push origin main

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
